services:
  redis:
    image: redis

  database:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db

  database_admin:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

  python-app:
    build:
      context: ./python-app
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./python-app
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
    depends_on:
      - redis
      - database

  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000

volumes:
  database_data: