services:
  redis:
    image: redis

  database:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - database_data:/var/lib/postgresql/data

  database_admin:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

  python-app:
    build:
      context: ./python-app
    volumes:
      - ./python-app:/app
      - /app/.venv
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./python-app
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
    depends_on:
      - redis
      - database
  
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    environment:
      - WATCHPACK_POLLING=true

    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000

volumes:
  database_data: