"""add unique constraint of latitude and longtitude on location model

Revision ID: 1243bc15382e
Revises: e16c2d89cdb7
Create Date: 2025-07-07 21:28:24.468416

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1243bc15382e'
down_revision: Union[str, Sequence[str], None] = 'e16c2d89cdb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lat_lng', 'location', ['latitude', 'longitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lat_lng', 'location', type_='unique')
    # ### end Alembic commands ###
