"""remove latitude and longitude index

Revision ID: 4bbb81ae4434
Revises: 1243bc15382e
Create Date: 2025-07-09 04:11:19.016166

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbb81ae4434'
down_revision: Union[str, Sequence[str], None] = '1243bc15382e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_location_all_fields'), table_name='location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_location_all_fields'), 'location', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###
